import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../worker/index.js';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../drizzle/0000_nebulous_scourge.sql',import.meta.url),'utf8'));const files=new Map();return {DB:{prepare(sql){return{bind(...args){return{first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:db.prepare(sql).run(...args)})};},first:async()=>db.prepare(sql).get()};}},BUCKET:{put:async(key,body,metadata)=>files.set(key,{bytes:await new Response(body).arrayBuffer(),metadata}),get:async(key)=>{const f=files.get(key);if(!f)return null;return{body:new Blob([f.bytes]).stream(),arrayBuffer:async()=>f.bytes,writeHttpMetadata:h=>h.set('content-type',f.metadata.httpMetadata.contentType)};},delete:async key=>files.delete(key)},files,db};}
function request(path,options={},user='owner'){return new Request('https://pdf.example.com'+path,{...options,headers:{...(user?{'oai-authenticated-user-id':user}:{}),...options.headers}});}
function upload(){const form=new FormData();form.set('file',new File(['%PDF-1.4\noriginal bytes'],'paper.pdf',{type:'application/pdf'}));form.set('target_language','Korean');return form;}
test('durable upload, owner isolation, downloads and unconfigured engine',async()=>{const env=fixture();const response=await worker.fetch(request('/api/jobs',{method:'POST',body:upload()}),env);assert.equal(response.status,201);const doc=await response.json();assert.equal(doc.status,'saved');assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM jobs').get().n,1);assert.equal((await worker.fetch(request('/api/jobs'),env).then(r=>r.json())).length,1);assert.equal((await worker.fetch(request('/api/jobs',{},'other'),env).then(r=>r.json())).length,0);assert.equal((await worker.fetch(request(doc.original_url,{},'other'),env)).status,404);assert.equal((await worker.fetch(request(doc.original_url,{},null),env)).status,401);assert.equal(await worker.fetch(request(doc.original_url),env).then(r=>r.text()),'%PDF-1.4\noriginal bytes');assert.equal((await worker.fetch(request(`/api/jobs/${doc.job_id}/start`,{method:'POST'}),env)).status,503);assert.equal((await worker.fetch(request('/api/jobs'),env).then(r=>r.json()))[0].status,'saved');});
test('rejects invalid PDF and cross-origin writes without records',async()=>{const env=fixture();const body=new FormData();body.set('file',new File(['not a PDF'],'fake.pdf'));assert.equal((await worker.fetch(request('/api/jobs',{method:'POST',body}),env)).status,400);assert.equal((await worker.fetch(request('/api/jobs',{method:'POST',body:upload(),headers:{origin:'https://other.example'}}),env)).status,403);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM jobs').get().n,0);});
test('completed artifacts archived and served without backend on later visits',async()=>{const env=fixture();env.OPENPDF2ZH_BACKEND_URL='https://engine.example';env.OPENPDF2ZH_BACKEND_TOKEN='test-token';const doc=await worker.fetch(request('/api/jobs',{method:'POST',body:upload()}),env).then(r=>r.json());const originalFetch=globalThis.fetch;let submissions=0;globalThis.fetch=async(url,options)=>{assert.equal(options.headers.Authorization,'Bearer test-token');if(url.endsWith('/api/jobs')){submissions++;return Response.json({job_id:'engine-1',status:'queued'});}if(url.includes('/api/jobs/'))return Response.json({status:'succeeded',artifacts:{translated_pdf:'https://evil.example/steal'},warnings:['overflow warning']});assert.equal(url,'https://engine.example/files/engine-1/translated_mono.pdf');return new Response('%PDF-translated');};try{assert.equal((await worker.fetch(request(`/api/jobs/${doc.job_id}/start`,{method:'POST'}),env)).status,200);await worker.fetch(request(`/api/jobs/${doc.job_id}/start`,{method:'POST'}),env);assert.equal(submissions,1);const done=await worker.fetch(request(`/api/jobs/${doc.job_id}`),env).then(r=>r.json());assert.equal(done.status,'succeeded');delete env.OPENPDF2ZH_BACKEND_URL;assert.equal(await worker.fetch(request(done.artifacts.translated_pdf),env).then(r=>r.text()),'%PDF-translated');assert.equal((await worker.fetch(request(`/api/jobs/${doc.job_id}`),env).then(r=>r.json())).status,'succeeded');}finally{globalThis.fetch=originalFetch;}});
